feat: update install-php-extensions

diff --git a/services/php/install-php-extensions b/services/php/install-php-extensions
--- a/services/php/install-php-extensions
+++ b/services/php/install-php-extensions
@@ -21,7 +21,7 @@ if ! which docker-php-ext-configure >/dev/null || ! which docker-php-ext-enable 
 	exit 1
 fi
 
-IPE_VERSION=2.2.2
+IPE_VERSION=2.2.8
 
 StandWithUkraine() {
 	if test -t 1 && ! grep -Eq '^VERSION=.*jessie' /etc/os-release; then
@@ -679,7 +679,7 @@ buildRequiredPackageLists() {
 				buildRequiredPackageLists_volatile="$buildRequiredPackageLists_volatile $PHPIZE_DEPS"
 			fi
 			if test -z "$(apk info 2>/dev/null | grep -E ^libssl)"; then
-				buildRequiredPackageLists_libssl='^libssl[0-9]+(\.[0-9]+)*$'
+				buildRequiredPackageLists_libssl="$(apk search | grep -E '^libssl[0-9]' | head -1 | cut -d- -f1)"
 			elif test -z "$(apk info 2>/dev/null | grep -E '^libressl.*-libtls')" && test -z "$(apk info 2>/dev/null | grep -E '^libressl.*-libssl')" && test -z "$(apk info 2>/dev/null | grep -E '^libretls-')"; then
 				buildRequiredPackageLists_libssl=$(apk search -q libressl*-libtls)
 			else
@@ -2002,11 +2002,11 @@ installOracleInstantClient() {
 		mv "$installOracleInstantClient_src" "$ORACLE_INSTANTCLIENT_LIBPATH"
 		echo 'done.'
 	fi
-	if ! test -e "$ORACLE_INSTANTCLIENT_LIBPATH/sdk"; then
+	if ! test -e "$ORACLE_INSTANTCLIENT_LIBPATH/sdk" && ! test -L "$ORACLE_INSTANTCLIENT_LIBPATH/sdk"; then
 		printf 'Downloading Oracle Instant SDK v%s... ' "$installOracleInstantClient_version"
 		installOracleInstantClient_src="$(getPackageSource $installOracleInstantClient_sdk)"
 		ln -sf "$installOracleInstantClient_src/sdk" "$ORACLE_INSTANTCLIENT_LIBPATH/sdk"
-		UNNEEDED_PACKAGE_LINKS="$UNNEEDED_PACKAGE_LINKS '$ORACLE_INSTANTCLIENT_LIBPATH/sdk'"
+		UNNEEDED_PACKAGE_LINKS="$UNNEEDED_PACKAGE_LINKS $ORACLE_INSTANTCLIENT_LIBPATH/sdk"
 		echo 'done.'
 	fi
 	case "$DISTRO" in
@@ -2056,7 +2056,7 @@ installMicrosoftSqlServerODBC() {
 		alpine)
 			rm -rf /tmp/src/msodbcsql.apk
 			if test $PHP_MAJMIN_VERSION -le 703; then
-				curl -sSLf -o /tmp/src/msodbcsql.apk https://download.microsoft.com/download/e/4/e/e4e67866-dffd-428c-aac7-8d28ddafb39b/msodbcsql17_17.10.5.1-1_amd64.apk
+				curl -sSLf -o /tmp/src/msodbcsql.apk https://download.microsoft.com/download/e/4/e/e4e67866-dffd-428c-aac7-8d28ddafb39b/msodbcsql17_17.10.6.1-1_amd64.apk
 			else
 				case $(uname -m) in
 					aarch64 | arm64 | armv8)
@@ -2066,7 +2066,7 @@ installMicrosoftSqlServerODBC() {
 						installMicrosoftSqlServerODBC_arch=amd64
 						;;
 				esac
-				curl -sSLf -o /tmp/src/msodbcsql.apk https://download.microsoft.com/download/3/5/5/355d7943-a338-41a7-858d-53b259ea33f5/msodbcsql18_18.3.2.1-1_$installMicrosoftSqlServerODBC_arch.apk
+				curl -sSLf -o /tmp/src/msodbcsql.apk https://download.microsoft.com/download/3/5/5/355d7943-a338-41a7-858d-53b259ea33f5/msodbcsql18_18.3.3.1-1_$installMicrosoftSqlServerODBC_arch.apk
 			fi
 			printf '\n' | apk add --allow-untrusted /tmp/src/msodbcsql.apk
 			rm -rf /tmp/src/msodbcsql.apk
@@ -2293,10 +2293,10 @@ installIonCubeLoader() {
 		*)
 			case $(uname -m) in
 				aarch64 | arm64 | armv8)
-					installIonCubeLoader_url="cdn.seatonjiang.com/ioncube/ioncube_loaders_lin_aarch64.tar.gz"
+					installIonCubeLoader_url="https://cdn.seatonjiang.com/ioncube/ioncube_loaders_lin_aarch64.tar.gz"
 					;;
 				*)
-					installIonCubeLoader_url="cdn.seatonjiang.com/ioncube/ioncube_loaders_lin_x86-64.tar.gz"
+					installIonCubeLoader_url="https://cdn.seatonjiang.com/ioncube/ioncube_loaders_lin_x86-64.tar.gz"
 					;;
 			esac
 			;;
@@ -2988,6 +2988,12 @@ installRemoteModule() {
 				fi
 			fi
 			;;
+		imap)
+			# Include Kerberos Support
+			addConfigureOption with-kerberos yes
+			# Include SSL Support
+			addConfigureOption with-imap-ssl yes
+			;;
 		inotify)
 			if test -z "$installRemoteModule_version"; then
 				if test $PHP_MAJMIN_VERSION -le 506; then
@@ -3207,6 +3213,14 @@ installRemoteModule() {
 				fi
 			fi
 			;;
+		oci8 | pdo_oci)
+			installOracleInstantClient
+			if test "$installRemoteModule_module" = oci8; then
+				addConfigureOption with-oci8 "instantclient,$ORACLE_INSTANTCLIENT_LIBPATH"
+			elif test "$installRemoteModule_module" = pdo_oci; then
+				addConfigureOption with-pdo-oci "instantclient,$ORACLE_INSTANTCLIENT_LIBPATH"
+			fi
+			;;
 		opencensus)
 			if test -z "$installRemoteModule_version"; then
 				installRemoteModule_version=alpha
@@ -3372,6 +3386,8 @@ installRemoteModule() {
 					installRemoteModule_version=3.12.4
 				elif test $PHP_MAJMIN_VERSION -lt 800; then
 					installRemoteModule_version=3.24.4
+				elif test $PHP_MAJMIN_VERSION -lt 801; then
+					installRemoteModule_version=3.25.3
 				fi
 			fi
 			;;
@@ -3913,7 +3929,7 @@ installRemoteModule() {
 							installRemoteModule_architecture=alpine-arm64
 							;;
 						*)
-							installRemoteModule_architecture=alpine
+							installRemoteModule_architecture=alpine-x86_64
 							;;
 					esac
 					;;
@@ -3929,6 +3945,10 @@ installRemoteModule() {
 					;;
 			esac
 			installRemoteModule_url="$(curl -sSLf -o - https://tideways.com/profiler/downloads | grep -Eo "\"[^\"]+/tideways-php-([0-9]+\.[0-9]+\.[0-9]+)-$installRemoteModule_architecture.tar.gz\"" | cut -d'"' -f2)"
+			if test -z "$installRemoteModule_url"; then
+				echo 'Failed to find the tideways tarball to be downloaded'
+				exit 1
+			fi
 			printf 'Downloading tideways from %s\n' "$installRemoteModule_url"
 			installRemoteModule_src="$(getPackageSource $installRemoteModule_url)"
 			if test -d "$installRemoteModule_src/dist"; then
